--------------------------------------------------------
--  File created - Wednesday-January-28-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TRANSACTIONS
--------------------------------------------------------

  CREATE TABLE "TRANSACTIONS" 
   (	"TRANSACTION_ID" NUMBER, 
	"PATRON_ID" NUMBER, 
	"BOOK_ID" VARCHAR2(20 BYTE), 
	"TRANSACTION_DATE" DATE, 
	"TRANSACTION_TYPE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "TRANSACTIONS"."TRANSACTION_ID" IS 'PK';
 
   COMMENT ON COLUMN "TRANSACTIONS"."PATRON_ID" IS 'FK';
 
   COMMENT ON COLUMN "TRANSACTIONS"."BOOK_ID" IS 'FK';
REM INSERTING into TRANSACTIONS
SET DEFINE OFF;
Insert into TRANSACTIONS (TRANSACTION_ID,PATRON_ID,BOOK_ID,TRANSACTION_DATE,TRANSACTION_TYPE) values (1,100,'A1111',to_date('24-FEB-19','DD-MON-RR'),1);
Insert into TRANSACTIONS (TRANSACTION_ID,PATRON_ID,BOOK_ID,TRANSACTION_DATE,TRANSACTION_TYPE) values (2,100,'A2222',to_date('25-FEB-19','DD-MON-RR'),2);
Insert into TRANSACTIONS (TRANSACTION_ID,PATRON_ID,BOOK_ID,TRANSACTION_DATE,TRANSACTION_TYPE) values (3,101,'A3333',to_date('08-FEB-19','DD-MON-RR'),3);
Insert into TRANSACTIONS (TRANSACTION_ID,PATRON_ID,BOOK_ID,TRANSACTION_DATE,TRANSACTION_TYPE) values (4,101,'A2222',to_date('20-FEB-19','DD-MON-RR'),1);
Insert into TRANSACTIONS (TRANSACTION_ID,PATRON_ID,BOOK_ID,TRANSACTION_DATE,TRANSACTION_TYPE) values (5,102,'A3333',to_date('20-FEB-19','DD-MON-RR'),1);
Insert into TRANSACTIONS (TRANSACTION_ID,PATRON_ID,BOOK_ID,TRANSACTION_DATE,TRANSACTION_TYPE) values (6,103,'A4444',to_date('04-FEB-19','DD-MON-RR'),2);
Insert into TRANSACTIONS (TRANSACTION_ID,PATRON_ID,BOOK_ID,TRANSACTION_DATE,TRANSACTION_TYPE) values (7,100,'A4444',to_date('04-FEB-19','DD-MON-RR'),1);
Insert into TRANSACTIONS (TRANSACTION_ID,PATRON_ID,BOOK_ID,TRANSACTION_DATE,TRANSACTION_TYPE) values (8,102,'A2222',to_date('24-FEB-19','DD-MON-RR'),2);
Insert into TRANSACTIONS (TRANSACTION_ID,PATRON_ID,BOOK_ID,TRANSACTION_DATE,TRANSACTION_TYPE) values (9,102,'A5555',to_date('14-FEB-19','DD-MON-RR'),1);
Insert into TRANSACTIONS (TRANSACTION_ID,PATRON_ID,BOOK_ID,TRANSACTION_DATE,TRANSACTION_TYPE) values (10,101,'A2222',to_date('09-FEB-19','DD-MON-RR'),1);
